### PR TITLE
chore: Update to app version 2.9.6

### PR DESCRIPTION
**Pull request by mkilchhofer**

### CODE REVIEW

**Comment by p53** [comment]
@mkilchhofer thanks! could you update `–openid-provider-timeout` value to e.g. 120s, seems tests are failing

**Comment by mkilchhofer** [comment]
> @mkilchhofer thanks! could you update `–openid-provider-timeout` value to e.g. 120s, seems tests are failing

It seems that the keycloak image does not exists anymore:

```bash
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community

$ kubectl apply -f .github/manifest.yaml
configmap/keycloak-config created
configmap/mock-config created
deployment.apps/mock created
deployment.apps/keycloak created
service/mock created
service/keycloak created
ingress.networking.k8s.io/nginx created

$ kubectl rollout status deployment/keycloak
Waiting for deployment "keycloak" rollout to finish: 0 of 1 updated replicas are available...

$ kubectl get po
NAME                        READY   STATUS         RESTARTS   AGE
keycloak-56f5876876-zzncm   0/1     ErrImagePull   0          72s
mock-6d6fdcd98c-zwq6m       1/1     Running        0          72s

$ kubectl get events
LAST SEEN   TYPE      REASON                    OBJECT                           MESSAGE
81s         Normal    Scheduled                 pod/keycloak-56f5876876-zzncm    Successfully assigned default/keycloak-56f5876876-zzncm to kind-control-plane
29s         Normal    Pulling                   pod/keycloak-56f5876876-zzncm    Pulling image "jboss/keycloak:16.1.1"
29s         Warning   Failed                    pod/keycloak-56f5876876-zzncm    Failed to pull image "jboss/keycloak:16.1.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/jboss/keycloak:16.1.1": failed to resolve reference "docker.io/jboss/keycloak:16.1.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
29s         Warning   Failed                    pod/keycloak-56f5876876-zzncm    Error: ErrImagePull
```

Does it really needs to be keycloak or can we try to use an existing OIDC provider or even a mock provider like https://github.com/Soluto/oidc-server-mock ?

**Comment by p53** [comment]
@mkilchhofer ah ok checked logs just briefly, so lets update it to latest keycloak, we cannot use oidc server mock because gatekeeper checks at start structure of OIDC server url and whether it is keycloak specific url (i am working on separate gatekeeper oidc proxy or base proxy which would not have keycloak specific functionalities, rewrote several things to be able to reuse components between them but still not yet there)

**Comment by mkilchhofer** [comment]
Ah maybe we can just change the url to `docker pull quay.io/keycloak/keycloak:16.1.1` and update the keycloak in a later step?

**Review by p53 — APPROVED** [review]

**Comment by p53** [comment]
FYI, i am already using keycloak 19 in E2E tests and i would like to update it soon to latest

**Pull request merged**
